<?php
// *Id*
/**
 * @file
 *   Download remote translations from server
 */

/**
 * Implementation of hook_menu().
 */
function l10n_update_menu() {
  $items['admin/build/translate/update'] = array(
    'title' => 'Update',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('l10n_update_import_form'),
    'access arguments' => array('translate interface'),
    'weight' => 20,
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Update form
 * 
 * @todo selectable packages
 * @todo check language support in server
 * @todo check file update dates
 */
function l10n_update_import_form() {
  module_load_include('inc', 'l10n_update');
  // For now we get package information provided by modules
  $packages = module_invoke_all('l10n_update');
  $languages = locale_language_list('name');
  // Skip English language
  if (isset($languages['en'])) {
    unset($languages['en']);
  }
  if ($packages && $languages) {
    $updates = l10n_update_fetch_all($packages, $languages); 
    $form['updates'] = array(
      '#type' => 'value',
      '#value' => $updates,
    );
    $form['modules'] = array(
      '#title' => t('Packages'),
      '#type' => 'fieldset',
    );
    $header = array(t('Module'), t('Version'), t('Updates'));
    foreach ($packages as $name => $module) {
      $title = t('<strong>%name</strong> (%version)', array('%name' => $module['name'], '%version' => $module['info']['version']));
      $rows[] = array(
        array('data' => $title, 'colspan' => 3),
      );
      if (!empty($updates[$name])) {
        foreach ($updates[$name] as $lang => $release) {          
          $rows[] = array(
            $languages[$lang],
            format_date($release['date']),
            l(t('Download'), $release['download_link']),
          ); 
        }
      }
    }
    $form['modules']['modules'] = array('#value' => theme('table', $header, $rows));
    
    $form['languages'] = array(
      '#title' => t('Languages'),
      '#type' => 'checkboxes',
      '#options' => $languages,
      '#description' => t('Select one or more languages to download and update.'),
    );
    $form['mode'] = array('#type' => 'radios',
      '#title' => t('Mode'),
      '#default_value' => LOCALE_IMPORT_KEEP,
      '#options' => array(
        LOCALE_IMPORT_OVERWRITE => t('Strings in the uploaded file replace existing ones, new ones are added'),
        LOCALE_IMPORT_KEEP => t('Existing strings are kept, only new strings are added')
      ),
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Update'),
    );
  } else {
    $form['warning'] = array('#value' => t('No packages to update.'));
  }
  return $form;
}

/**
 * Update form
 */
function l10n_update_import_form_submit($form, $form_state) {
  module_load_include('inc', 'l10n_update');
  $packages = module_invoke_all('l10n_update');
  $languages = array_filter($form_state['values']['languages']);
  $mode = $form_state['values']['mode'];
  if ($languages && $packages) {
    foreach ($packages as $module) {
      foreach ($languages as $lang) {
        $url = l10n_update_download_url($module['name'], $lang);
        $operations[] = array('_l10n_update_batch_download_import', array($url, $lang));
      }
    }
    if (!empty($operations)) {
      $batch = l10n_update_create_batch($operations);
      batch_set($batch);
    }
  }
  else {
    drupal_set_message(t('No packages or languages selected.'), 'error');
  }
}

/**
 * Fetch update information for all projects / all languages
 * 
 * @return array()
 *   Available releases indexed by project and language
 */
function l10n_update_fetch_all($projects, $languages) {
  module_load_include('inc', 'l10n_update');
  $langcode = implode(',', array_keys($languages));
  $updates = array();
  if ($available = _l10n_update_fetch_releases($projects, $langcode)) {
    foreach ($projects as $project) {
      foreach ($languages as $lang => $language) {
        if (!empty($available[$project['name']]['releases'][$lang])) {
          $updates[$project['name']][$lang] = _l10n_update_extract_release($available[$project['name']], $lang, $project['info']['version']);
        }
      }
    }
  }
  return $updates;
}