<?php
// *Id*
/**
 * @file
 *   Download remote translations from server
 *   
 * @todo Implement updates on cron
 * @todo Fetch information from info files
 */

/**
 * Implementation of hook_menu().
 */
function l10n_update_menu() {
  $items['admin/build/translate/update'] = array(
    'title' => 'Update',
    'description' => 'Available updates',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('l10n_update_admin_import_form'),
    'access arguments' => array('translate interface'),
    'file' => 'l10n_update.admin.inc',
    'weight' => 20,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/build/translate/update/refresh'] = array(
    'title' => 'Update',
    'description' => 'Available updates',
    'weight' => 10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/build/translate/update/settings'] = array(
    'title' => 'Settings',
    'description' => 'Update configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('l10n_update_admin_settings_form'),
    'access arguments' => array('translate interface'),
    'file' => 'l10n_update.admin.inc',
    'weight' => 20,
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implementation of hook_cron()
 */
function l10n_update_cron() {
  if ($time = variable_get('l10n_update_check_frequency', 0)) {
    if (time() - variable_get('l10n_update_last_check', 0) > $time) {
      module_load_include('inc', 'l10n_update');
      _l10n_update_refresh();
    }    
  }
}

/**
 * Fetch update information for all projects / all languages
 * 
 * @return array()
 *   Available releases indexed by project and language
 */
function l10n_update_available_releases($refresh = FALSE) {  
  if (!$refresh && ($cache = cache_get('l10n_update_available_releases'))) {
    return $cache->data;
  }
  else {
    module_load_include('inc', 'l10n_update');
    return _l10n_update_refresh();
  }
}

/**
 * Get list of projects
 * 
 * Atm, this is provided by modules implementing the l10n_update hook.
 * But in the future we might be able to fetch it from install files.
 */
function l10n_update_get_projects() {
  static $projects;  
  if (!isset($projects)) {
    $projects = module_invoke_all('l10n_update');
  }
  return $projects;
}

/**
 * Get update history
 * 
 * Returns an array indexed by project name
 * For each project there are updates indexed by language
 */
function l10n_update_get_history($refresh = FALSE) {
  static $status;
  
  if ($refresh ||!isset($status)) {
    $status = array();
    $result = db_query("SELECT * FROM {l10n_update_project}");
    while ($project = db_fetch_object($result)) {
      $status[$project->name] = $project;
    }
    $result = db_query("SELECT * FROM {l10n_update_download}");
    while ($update = db_fetch_object($result)) {
      $status[$update->project]->updates[$update->language] = $update;
    }
  }
  
  return $status;
}

/**
 * Refresh project information
 */
function l10n_update_refresh_history() {
  $projects = l10n_update_get_projects();
  $updates = l10n_update_get_history();
  
  $changes = 0;
  foreach ($projects as &$project) {
    $name = $project['name'];
    if (empty($updates[$name])) {
      // Project is not there, create it
      $save = array('name' => $name, 'version' => $project['info']['version']);
      drupal_write_record('l10n_update_project', $save);
      $changes++;     
    }
    elseif ($updates[$name]->version != $project['info']['version']) {
      // Update project version
      $updates[$name]->version = $project['info']['version'];
      drupal_write_record('l10n_update_project', $updates[$name], 'name');
      $changes++;
    }
  }
  // If any change it will be refreshed
  return l10n_update_get_history($changes);
}

/**
 * Get language list
 */
function l10n_update_language_list($field = 'name') {
  $languages = locale_language_list('name');
  // Skip English language
  if (isset($languages['en'])) {
    unset($languages['en']);
  }
  return $languages;
}

/**
 * Implementation of the hook_theme() registry.
 */
function l10n_update_theme() {
  return array(
    'l10n_update_project_status' => array(
      'arguments' => array('projects' => NULL, 'languages' => NULL, 'history' => NULL, 'available' => NULL, 'updates' => NULL),
      'file' => 'l10n_update.admin.inc',
    ),
    'l10n_update_tag_date' => array(
      'arguments' => array('tag' => NULL, 'date' => NULL),
      'file' => 'l10n_update.admin.inc',
    ),
    'l10n_update_version_status' => array(
      'arguments' => array('status' => NULL),
      'file' => 'l10n_update.admin.inc',    
    ),
  );
}

/**
 * Prints a warning message when there is no data about available updates.
 */
function _l10n_update_no_data() {
  $destination = drupal_get_destination();
  return t('No information is available about potential new and updated translations for currently installed modules and themes. To check for updates, you may need to <a href="@run_cron">run cron</a> or you can <a href="@check_manually">check manually</a>. Please note that checking for available updates can take a long time, so please be patient.', array(
    '@run_cron' => url('admin/reports/status/run-cron', array('query' => $destination)),
    '@check_manually' => url('admin/build/translate/update', array('query' => $destination)),
  ));
}