<?php

function mail2web_extras_mail2web_alter(&$node, $op) {
  switch ($op) {
    case 'post':
      /*
       * Below are what each pattern tries to match.
       * gmail 1 => On 3/10/09,
       * gmail 2 => On Mon, Mar 9, 2009 at 10:14 PM,
       * mac_mail => On Feb 17, 2009, at 2:30 PM, foo@example.com wrote:
       * outlook_express => ----- Original Message -----
       *
       */
      // Build an array of different possible matching expressions
      $expressions = array(
        'gmail_1' => "/On \d{1,2}[\/\-]{1}\d{1,2}[\/\-]{1}\d{1,2},/",
        'gmail_2' => "/On \w{3}, \w{3} \d{1,2}, \d{4} at \d{1,2}:\d{1,2} [AP]M/",
        'mac_mail' => "/On [A-Z][a-z]{2} [0-9]{1,2}, [0-9]{4}, at [0-9]{1,2}:[0-9]{2} [AP]M, [a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4} wrote/",
        'outlook_express' => '/-----\s?Original Message\s?-----/',
      );

      $match = 0;
      foreach($expressions as $name => $expression) {
        if ($match < 1) {
          $split = preg_split($expression, $node->body);
          //$split = preg_split("/\>/",$split[0]);
          if (count($split) > 1) {
            // An expression was matched, so break the loop.
            $match = 1;
          }
        }
      }

      if (!empty($split[1])) {
        $node->body = $split[0];
        // A hack.  Tell mail2web the message is already cleaned.
        $node->mail2web_cleaned = 1;
      }
      break;
  }
}