<?php

/**
 * Update to resolve install profile namespace collision.
 */
function atrium_update_6001() {
  if (variable_get('install_profile', FALSE) == 'atrium') {
    variable_set('install_profile', 'atrium_installer');
  }
  return array();
}

/**
 * Update 6002: Enable new modules.
 */
function atrium_update_6002() {
  drupal_install_modules(array(
    'atrium_groups',
    'atrium_members',
  ));
  return array();
}
